import {
  IProfilingResult,
  ProfilingResult,
} from '../DataTransferObjects/V1/ProfilingResult.js';
import ECO from '../ECO.js';
import { ControllerBase } from './ControllerBase.js';

/**
 * Provides methods to list and download profiling results generated by ProfilingPlugin
 */
export class ProfilingResultsController extends ControllerBase {
  constructor(client: ECO) {
    super(client);
  }
  /**
   * Returns the list of generated profiling results.
   */
  public async getProfilingResults() {
    return this.GET<ProfilingResult[], IProfilingResult[]>(
      `/api/v1/profiling-results`,
      (client, results) =>
        results.map((result) => new ProfilingResult(client, result)),
    );
  }

  public async getProfile(filename: string) {
    return this.GET<any, any>(`/api/v1/profiling-results/${filename}`);
  }
}
